// ==UserScript==
// @name         NodeSeek Max
// @namespace    https://github.com/Ethan2258/Nodeseek-max
// @version      1.0.0
// @description  NodeSeek 全能增强：融合 NodeSeek++、外链自动跳转、黑名单通知屏蔽与侧栏热榜，并提供可配置的现代化界面主题。
// @author       Ethan
// @license      GPL-3.0-only
// @homepageURL  https://github.com/Ethan2258/Nodeseek-max
// @supportURL   https://github.com/Ethan2258/Nodeseek-max/issues
// @match        https://www.nodeseek.com/*
// @match        https://www.deepflood.com/*
// @include      /^https?:\/\/www\.google\..{2,7}url/
// @match        *://www.jianshu.com/go-wild*
// @match        *://link.zhihu.com/*
// @match        *://t.cn/*
// @match        *://weibo.cn/sinaurl*
// @match        *://mail.qq.com/cgi-bin/*
// @match        *://wx.mail.qq.com/xmspamcheck/xmsafejump*
// @match        *://c.pc.qq.com/middlem.html*
// @match        *://c.pc.qq.com/middlect.html*
// @match        *://c.pc.qq.com/pc.html*
// @match        *://c.pc.qq.com/ios.html*
// @match        *://c.pc.qq.com/android.html*
// @match        *://app.yinxiang.com/OutboundRedirect.action*
// @match        *://jump.bdimg.com/safecheck/*
// @match        *://jump2.bdimg.com/safecheck/*
// @match        *://tieba.baidu.com/mo/q/checkurl*
// @match        *://link.csdn.net/*
// @match        *://www.youtube.com/redirect*
// @match        *://mp.weixin.qq.com/s/*
// @match        *://mp.weixin.qq.com/mp/readtemplate*
// @match        *://weixin110.qq.com/cgi-bin/mmspamsupport-bin/newredirectconfirmcgi*
// @match        *://open.work.weixin.qq.com/wwopen/uriconfirm*
// @match        *://developers.weixin.qq.com/community/middlepage/href*
// @match        *://www.itdaan.com/link/*
// @match        *://www.douban.com/link2/*
// @match        *://www.360doc.com/content/*
// @match        *://www.pixiv.net/jump.php*
// @match        *://m.sogou.com/*/tc*
// @match        *://m.sogou.com*/tc*
// @match        *://www.chinaz.com/go.shtml*
// @match        *://www.oschina.net/action/GoToLink*
// @match        *://link.juejin.cn/*
// @match        *://docs.qq.com/scenario/link.html*
// @match        *://www.pc6.com/goread.html*
// @match        *://afdian.net/link*
// @match        *://afdian.com/link*
// @match        *://ifdian.net/link*
// @match        *://gitee.com/link*
// @match        *://www.tianyancha.com/security*
// @match        *://aiqicha.baidu.com/safetip*
// @match        *://www.qcc.com/web/transfer-link*
// @match        *://link.uisdc.com/*
// @match        *://blog.51cto.com/transfer*
// @match        *://leetcode.cn/link*
// @match        *://huaban.com/go*
// @match        *://security.feishu.cn/link/safety*
// @match        *://redirect.epicgames.com/*
// @match        *://steamcommunity.com/linkfilter/*
// @match        *://*.yuque.com/r/goto*
// @match        *://hd.nowcoder.com/link.html*
// @match        *://game.bilibili.com/linkfilter/*
// @match        *://www.bilibili.com/york/link-middle-page/pc*
// @match        *://sspai.com/link*
// @match        *://niu.sspai.com/link*
// @match        *://jump.5ch.net/*
// @match        *://www.kdocs.cn/office/link*
// @match        *://shimo.im/outlink/black*
// @match        *://google.urlshare.cn/umirror_url_check*
// @match        *://www.coolapk.com/link*
// @match        *://wpfx.org/go*
// @match        *://cloud.tencent.com/developer/tools/blog-entry*
// @match        *://support.qq.com/products/*/link-jump*
// @match        *://txc.qq.com/products/*/link-jump*
// @match        *://yq.aliyun.com/go/articleRenderRedirect*
// @match        *://www.yiqicha.com/thirdPage*
// @match        *://www.iplaysoft.com/link*
// @match        *://hellogithub.com/periodical/statistics/click*
// @match        *://zmingcx.com/go.html*
// @match        *://ref.gamer.com.tw/redir.php*
// @match        *://ababtools.com/?plugin=redirect_page*
// @match        *://help.aliyun.com/redirect*
// @match        *://linux.do/*
// @connect      api.nodeimage.com
// @connect      rss.nodeseek.com
// @connect      api.bimg.eu.org
// @connect      raw.githubusercontent.com
// @connect      cdn.jsdelivr.net
// @grant        GM_addStyle
// @grant        GM_getValue
// @grant        GM_notification
// @grant        GM_registerMenuCommand
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @grant        unsafeWindow
// @run-at       document-start
// @noframes
// @compatible   chrome Latest
// @compatible   firefox Latest
// @compatible   edge Latest
// @downloadURL  https://raw.githubusercontent.com/Ethan2258/Nodeseek-max/main/nodeseek-max.user.js
// @updateURL    https://raw.githubusercontent.com/Ethan2258/Nodeseek-max/main/nodeseek-max.meta.js
// ==/UserScript==
